import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Sale from "./../../public/icons/sale.svg";
import Right from "./../../public/icons/right.svg";
import Search from "./../../public/icons/Search.svg";
import User from "./../../public/icons/User.svg";
import Shop from "./../../public/icons/Shop.svg";
import Logo from "./../../public/images/logo.svg";
import Banner from "./../../public/images/banner.png"
import Img from "./../../public/images/Img.png"
import Images from "./../../public/images/image.png"
import Cards from "./../../public/images/Cards.png"
import Cart from "./../../public/images/cart.png"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${spaceGrotesk.variable} antialiased`} // Space Grotesk shriftini qo'shish
      >
        <div className="bg-[#38CB89]">
          <div className="container py-2">
            <div className="flex justify-center items-center gap-3">
              <Image src={Sale} alt="" />
              <h3 className="text-[14px] font-semibold leading-[22px] text-[#000000]">
                30% off storewide — Limited time!
              </h3>
              <div className="flex items-center gap-1">
                <h3 className="text-[14px] font-semibold leading-[24px] text-[#000000]">
                  Shop Now
                </h3>
                <Image src={Right} alt="" />
              </div>
            </div>
          </div>
        </div>
        <div>
          <div className="container py-5 flex justify-between items-center">
            <div>
              <Link href="/"> <Image src={Logo} alt="" /></Link>
            </div>
            <div className=" mx-auto px-4 py-3 flex justify-between items-center">
              <ul className="flex space-x-6 text-sm font-medium text-gray-800">
                <li>
                  <Link
                    href="/"
                    className="font-space-grotesk text-xs font-medium leading-6 text-left underline-from-font decoration-skip-none text-[#141718]"
                  >
                    Home
                  </Link>
                </li>
                <li className="relative group">
                  <span className="font-space-grotesk text-xs font-medium leading-6 text-left underline-from-font decoration-skip-none text-[#141718]">
                    Shop
                  </span>
                </li>
                <li className="relative group">
                  <span className="font-space-grotesk text-xs font-medium leading-6 text-left underline-from-font decoration-skip-none text-[#141718]">
                    Product
                  </span>
                </li>
                <li>
                  <Link
                    href="/contact-us"
                    className="font-space-grotesk text-xs font-medium leading-6 text-left underline-from-font decoration-skip-none text-[#141718]"
                  >
                    Contact Us
                  </Link>
                </li>
              </ul>
            </div>
            <div className="flex gap-4">
              <Image src={Search} alt="" />
              <Link href="/admin"> <Image src={User} alt="" /></Link>
              <Image src={Shop} alt="" />
            </div>
          </div>
        </div>
        <div>
          <div>
            <Image className="w-full h-full" src={Banner} alt="" />
          </div>
          <div className="absolute top-80 left-10">
            <h1 className="text-6xl font-medium leading-[65px] tracking-[-2px] text-left text-[#FFFFFF]">More than <br />
              just a game. <br />
              It’s a lifestyle.</h1>
            <p className="text-base font-normal leading-[32px] text-left py-2 text-[#FEFEFE]">Whether you’re just starting out, have played <br /> your whole life or you're a Tour pro, your <br /> swing is like a fingerprint.</p>
            <button className="w-[234px] h-[56px] py-3 px-14 gap-2 rounded-[8px]  text-[#141718] bg-[#38CB89]">Shopping Now</button>
          </div>
        </div>
        <div>{children}</div>
        <div className="container py-20">
          <div>
            <h2 className="text-4xl font-medium leading-[44px] tracking-[-0.4px] text-center text-[#23262F]">Shop by Categories</h2>
          </div>
          <div className="grid grid-cols-3 place-items-center py-12">
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
            <div>
              <Image src={Img} alt="" />
              <p className="text-base font-medium leading-[28px] py-6 text-center text-[#23262F]">Footwear</p>
            </div>
          </div>

        </div>
        <div className="container">
          <div className="flex items-center gap-36 bg-[#141718]">
            <div>
              <Image src={Images} alt="" />
            </div>
            <div className="absolute left-[900px]">
              <h3 className="text-sm font-bold leading-[16px] text-left text-[#38CB89]">Limited Edition</h3>
              <h2 className=" text-4xl font-medium leading-[44px] tracking-[-0.4px] text-left text-[#FEFEFE] py-8">Hurry up! 30% OFF</h2>
              <p className=" text-sm font-normal leading-[26px] text-left text-[#FEFEFE]">Find clubs that are right for your game</p>
              <Image src={Cards} alt="" />
              <div className="py-6">
                <button className="w-[234px] h-[56px] py-3 px-14 gap-2 rounded-[8px]  text-[#141718] bg-[#38CB89]">Shopping Now</button>
              </div>
            </div>
          </div>
        </div>
        <div className="container py-6">
          <Image src={Cart} alt="" />
        </div>
        <footer className="bg-black text-white py-12 px-6">
  <div className="container mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
    {/* Brend va ijtimoiy tarmoqlar */}
    <div>
      <h1 className="text-2xl font-bold mb-4">3legant.</h1>
      <p className="mb-6">
        More than just a game. <br /> It’s a lifestyle.
      </p>
      <div className="flex space-x-4">
        <a href="#" aria-label="Instagram">
          <i className="fab fa-instagram text-xl"></i>
        </a>
        <a href="#" aria-label="Facebook">
          <i className="fab fa-facebook-f text-xl"></i>
        </a>
        <a href="#" aria-label="YouTube">
          <i className="fab fa-youtube text-xl"></i>
        </a>
      </div>
    </div>

    {/* Sahifa havolalari */}
    <div>
      <h3 className="text-lg font-semibold mb-4">Page</h3>
      <ul className="space-y-2">
        <li><a href="#" className="hover:underline">Home</a></li>
        <li><a href="#" className="hover:underline">Shop</a></li>
        <li><a href="#" className="hover:underline">Product</a></li>
        <li><a href="#" className="hover:underline">Articles</a></li>
        <li><a href="#" className="hover:underline">Contact Us</a></li>
      </ul>
    </div>

    {/* Ma'lumot havolalari */}
    <div>
      <h3 className="text-lg font-semibold mb-4">Info</h3>
      <ul className="space-y-2">
        <li><a href="#" className="hover:underline">Shipping Policy</a></li>
        <li><a href="#" className="hover:underline">Return & Refund</a></li>
        <li><a href="#" className="hover:underline">Support</a></li>
        <li><a href="#" className="hover:underline">FAQs</a></li>
      </ul>
    </div>

    {/* Ofis ma'lumotlari */}
    <div>
      <h3 className="text-lg font-semibold mb-4">Office</h3>
      <ul className="space-y-2">
        <li>
          43111 Hai Trieu Street, <br /> District 1, HCMC, Vietnam
        </li>
        <li>84-756-3237</li>
      </ul>
    </div>
  </div>

 
  <div className="border-t border-gray-700 mt-12 pt-6 flex flex-col md:flex-row justify-between items-center">
    <p className="text-sm">&copy; 2023 3legant. All rights reserved</p>
    <div className="flex space-x-6 mt-4 md:mt-0">
      <a href="#" className="text-sm hover:underline">Privacy Policy</a>
      <a href="#" className="text-sm hover:underline">Terms & Conditions</a>
    </div>
   
  </div>
</footer>


      </body>
    </html>
  );
}
